### ISSUE TITLE
Add product create button not working

### ISSUE THREAD

**Issue by TR94** [TR94/kit-rate-pp5-frontend#55]
Clicking on the "create" button of the "Add product" form doesn't submit the data. 

Error in the console stating "An invalid form control with name='category' is not focusable.

Investigate and fix error - confirm with a successfully submitted product

**Comment by TR94** [comment]
Removing "required" from the category form (line 128 in ProductCreateForm.js) solves the issue however the form validation needs further investigation instead

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
Hi, i want to work on it if there is no one currently worrking on it

**Comment by TR94** [comment]
Added defaultValue attribute to the productCreateForm to fixed the "not focusable issue". Required attribute remains for form validation
